// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2pC2Z08gi3f3KFYHghfxAiyUBKiD4nHI',
    appId: '1:576521761023:web:2b6f33afb32d3c5e9c1cca',
    messagingSenderId: '576521761023',
    projectId: 'fidelway-2yq',
    authDomain: 'fidelway-2yq.firebaseapp.com',
    storageBucket: 'fidelway-2yq.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE7kMfCepF2xUdp1IcJ7H0z2wcGJAklRM',
    appId: '1:576521761023:android:c977e9002b90d0569c1cca',
    messagingSenderId: '576521761023',
    projectId: 'fidelway-2yq',
    storageBucket: 'fidelway-2yq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPc72V1bAFjKYcE8sYX2Q-oPCQVmeNwBY',
    appId: '1:576521761023:ios:048ec151e176081e9c1cca',
    messagingSenderId: '576521761023',
    projectId: 'fidelway-2yq',
    storageBucket: 'fidelway-2yq.firebasestorage.app',
    iosBundleId: 'com.alamio.fidelway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPc72V1bAFjKYcE8sYX2Q-oPCQVmeNwBY',
    appId: '1:576521761023:ios:048ec151e176081e9c1cca',
    messagingSenderId: '576521761023',
    projectId: 'fidelway-2yq',
    storageBucket: 'fidelway-2yq.firebasestorage.app',
    iosBundleId: 'com.alamio.fidelway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2pC2Z08gi3f3KFYHghfxAiyUBKiD4nHI',
    appId: '1:576521761023:web:b3915a2105948ba39c1cca',
    messagingSenderId: '576521761023',
    projectId: 'fidelway-2yq',
    authDomain: 'fidelway-2yq.firebaseapp.com',
    storageBucket: 'fidelway-2yq.firebasestorage.app',
  );
}
